state:
    sceneFilename: "Stata_GroundFloor"
    camWidth: 640
    camHeight: 480
    camFOV: 70.0
    camDepthScale: 0.20

renderer:
    0:
        inputPort: "10253"
        outputPort: "10254"

objects:
    0:
         ID: uav1
         prefabID: "BlackEagle"
         size_x: 5
         size_y: 5
         size_z: 5
    1:
         ID: gate1
         prefabID: "gate"
         size_x: 200
         size_y: 200
         size_z: 200
        
camera_model:
    0:
        ID: cam1
        channels: 3
        renderer: 0
        freq: 30
        outputShaderType: -1
        hasCollisionCheck: False
        initialPose: [-8.5, -18.5, -2, 1.0, 0, 0, 0]

vehicle_model:
    uav1:
        type: "uav"
        initialPose: [-6.5, -18.5, -1, 1.0, 0, 0, 0]
        imu_freq: 200
        objectsInfo:
            uav1:
                relativePose: [0, 0, 0, 0.707, 0, 0, -0.707]