state:
    # sceneFilename: "Abandoned_Factory_Morning"
    sceneFilename: "Stata_GroundFloor"
    camWidth: 640
    camHeight: 480
    camFOV: 70.0
    camDepthScale: 0.20

renderer:
    0:
        inputPort: "10253"
        outputPort: "10254"

camera_model:
    0:
        ID: cam1
        channels: 3
        renderer: 0
        freq: 30
        outputShaderType: -1
        hasCollisionCheck: False

vehicle_model:
    car1:
        type: "car"
        initialPose: [-6.5, -18.5, -0.2, 0.707, 0, 0, -0.707]
        imu_freq: 200
        cameraInfo:
            cam1:
                relativePose: [0, 0, 0, 1, 0, 0, 0]