state:
    # sceneFilename: "Abandoned_Factory_Morning"
    sceneFilename: "Stata_GroundFloor"
    camWidth: 640
    camHeight: 480
    camFOV: 70.0
    camDepthScale: 0.20
    map:
        filename: "Stata_GroundFloor.png"
        x_min: -31.0
        x_max: 78.5
        y_min: -68.1
        y_max: 78.8
        map_margin: 0
        map_scale: 3

renderer:
    0:
        inputPort: "10253"
        outputPort: "10254"

objects:
    0:
         ID: Gate1
         prefabID: gate
         size_x: 200
         size_y: 200
         size_z: 200
         renderer: 0
         outputIndex: 0
    1:
         ID: uav1
         prefabID: Blackeagle
         size_x: 5
         size_y: 5
         size_z: 5

camera_model:
    0:
        ID: cam1
        channels: 3
        renderer: 0
        freq: 30
        outputShaderType: -1
    1:
        ID: cam2
        channels: 3
        renderer: 0
        initialPose: [18.5,-10.5,-2,0.707,0,0,0.707]
        freq: 30
        outputShaderType: -1

vehicle_model:
    uav1:
        type: "uav"
        initialPose: [18.5,-6.5,-2,1.0,0,0,0]
        imu_freq: 200
        config_file: "multicopterDynamicsSim.yaml"
        objectsInfo: 
            uav1:
                relativePose: [0,0,0.3,1,0,0,0]
        cameraInfo:
            cam1:
                relativePose: [0,0,0,1,0,0,0]