state:
    sceneFilename: "Stata_GroundFloor"
    camWidth: 640
    camHeight: 480
    camFOV: 70.0
    camDepthScale: 0.20

renderer:
    0:
        inputPort: "10253"
        outputPort: "10254"

camera_model:
    0:
        ID: cam0
        channels: 3
        renderer: 0
        freq: 30
        outputShaderType: -1
        hasCollisionCheck: False
    1:
        ID: cam1
        channels: 3
        renderer: 0
        freq: 30
        outputShaderType: -1
        hasCollisionCheck: False

vehicle_model:
    uav1:
        type: "uav"
        initialPose: [-6.5, -18.5, -2.0, 1.0, 0, 0, 0]
        imu_freq: 200
        cameraInfo:
            cam0:
                relativePose: [0.2, 0, 0, 1, 0, 0, 0]
    car1:
        type: "car"
        initialPose: [-6.5, -18.5, -0.2, 1.0, 0, 0, 0]
        imu_freq: 200
        cameraInfo:
            cam1:
                relativePose: [0, 0, 0, 1, 0, 0, 0]
    uav2:
        type: "uav"
        initialPose: [-6.5, -12.5, -2.0, 1.0, 0, 0, 0]
        imu_freq: 200