state:
    # sceneFilename: "Abandoned_Factory_Morning"
    sceneFilename: "Stata_GroundFloor"
    camWidth: 1024
    camHeight: 768
    camFOV: 70.0
    camDepthScale: 0.20

renderer:
    0:
        inputPort: "10253"
        outputPort: "10254"

camera_model:
    0:
        ID: cam0
        channels: 3
        initialPose: [0.0, 0.0, 0.0, 1, 0, 0, 0]
        renderer: 0
        freq: 30
        outputShaderType: -1
        hasCollisionCheck: False

vehicle_model:
    uav1:
        type: "uav"
        initialPose: [-6.5, -18.5, -1.0, 0.707, 0.0, 0.0, -0.707]
        imu_freq: 200
        checkCollision: False
        cameraInfo:
            cam0:
                relativePose: [0, 0, 0, 1, 0, 0, 0]

