state:
    # sceneFilename: "Hazelwood_Loft_Full_Night"
    # sceneFilename: "Museum_Day_Multiroom"
    # sceneFilename: "Museum_Day_Small"
    # sceneFilename: "NYC_Subway"
    sceneFilename: "Butterfly_World"
    # sceneFilename: "Abandoned_Factory_Sunset"
    # sceneFilename: "Stata_GroundFloor"
    # sceneFilename: "Stata_Basement"
    camWidth: 1024
    camHeight: 150
    camFOV: 60.0
    camDepthScale: 0.20

renderer:
    0:
        inputPort: "10253"
        outputPort: "10254"

camera_model:
    0:
        ID: Camera_Left_RGB
        channels: 3
        isDepth: false
        outputIndex: 0
        hasCollisionCheck: false
        doesLandmarkVisCheck: false
        initialPose: [0, 0, 0, 1, 0, 0, 0]
        renderer: 0
        freq: 30
        outputShaderType: -1
    1:
        ID: Camera_Left_OpticalFlow
        channels: 3
        isDepth: false
        outputIndex: 1
        hasCollisionCheck: false
        doesLandmarkVisCheck: false
        initialPose: [0, 0, 0, 1, 0, 0, 0]
        renderer: 0
        freq: 30
        outputShaderType: 6
    2:
        ID: Camera_Left_Depth
        channels: 1
        isDepth: false
        outputIndex: 2
        hasCollisionCheck: false
        doesLandmarkVisCheck: false
        initialPose: [0, 0, 0, 1, 0, 0, 0]
        renderer: 0
        freq: 30
        outputShaderType: 3   
    3:
        ID: Camera_Left_SurfaceNormal
        channels: 3
        isDepth: false
        outputIndex: 2
        hasCollisionCheck: false
        doesLandmarkVisCheck: false
        initialPose: [0, 0, 0, 1, 0, 0, 0]
        renderer: 0
        freq: 30
        outputShaderType: 4
    4:
        ID: Camera_Left_Segmentation
        channels: 3
        isDepth: false
        outputIndex: 2
        hasCollisionCheck: false
        doesLandmarkVisCheck: false
        initialPose: [0, 0, 0, 1, 0, 0, 0]
        renderer: 0
        freq: 30
        outputShaderType: 1    
    5:
        ID: Camera_Left_Gray
        channels: 3
        isDepth: false
        outputIndex: 2
        hasCollisionCheck: false
        doesLandmarkVisCheck: false
        initialPose: [0, 0, 0, 1, 0, 0, 0]
        renderer: 0
        freq: 30
        outputShaderType: 5

objects:
    0:
         ID: Gate1
         prefabID: gate
         size_x: 100
         size_y: 100
         size_z: 100
         renderer: 0
         outputIndex: 0

vehicle_model:
    uav1:
        type: "uav"
        initialPose: [1.5, 0.0, -1.0, 0.707, 0, 0, 0.707]
        imu_freq: 200
        cameraInfo:
            Camera_Left_RGB:
                relativePose: [0.2, 0, 0, 1, 0, 0, 0]
                freq: 30
            Camera_Left_OpticalFlow:
                relativePose: [-0.2, 0, 0, 1, 0, 0, 0]
                freq: 30
            Camera_Left_Depth:
                relativePose: [-0.2, 0, 0, 1, 0, 0, 0]
                freq: 30
            Camera_Left_SurfaceNormal:
                relativePose: [-0.2, 0, 0, 1, 0, 0, 0]
                freq: 30
            Camera_Left_Segmentation:
                relativePose: [-0.2, 0, 0, 1, 0, 0, 0]
                freq: 30
            Camera_Left_Gray:
                relativePose: [-0.2, 0, 0, 1, 0, 0, 0]
                freq: 30
