state:
    # sceneFilename: "Abandoned_Factory_Morning"
    sceneFilename: "Stata_GroundFloor"
    camWidth: 640
    camHeight: 480
    camFOV: 70.0
    camDepthScale: 0.20

renderer:
    0:
        inputPort: "10253"
        outputPort: "10254"
    1:
        inputPort: "10255"
        outputPort: "10256"

camera_model:
    0:
        ID: cam0
        channels: 3
        renderer: 0
        freq: 30
        outputShaderType: -1
        hasCollisionCheck: False
    1:
        ID: cam1
        channels: 3
        renderer: 0
        freq: 30
        outputShaderType: -1
        hasCollisionCheck: False
    2:
        ID: cam2
        channels: 3
        renderer: 1
        freq: 30
        outputShaderType: -1
        hasCollisionCheck: False

vehicle_model:
    uav1:
        type: "uav"
        initialPose: [50.0,-49.0,-5.0,0,0,0,1]
        imu_freq: 200
        cameraInfo:
            cam0:
                relativePose: [0,0.2,0,1,0,0,0]
            cam1:
                relativePose: [0,-0.2,0,1,0,0,0]
    
    car1:
        type: "car"
        initialPose: [18.5,-6.5,-3.5,1.0,0,0,0]
        imu_freq: 200
        cameraInfo:
            cam2:
                relativePose: [0,0,0,1,0,0,0]